### PR TITLE
sonarqube_qualitygate/sonarqube_qualitygate_condition refactored

### LINKED ISSUE #154: sonarqube_qualitygate/qonarqube_qualitygate_condition essentially broken since SonarQube 9.9
Hi

SonarQube made a change in the `9.9` release ([SONAR-17818](https://sonarsource.atlassian.net/browse/SONAR-17818)) which automatically adds their "clean as you code" conditions to any quality gate that you create.
This basically makes it impossible to set different values using the terraform provider.

This is what we have been doing:
```
resource "sonarqube_qualitygate" "default" {
  name       = "My way"
  is_default = true
}

resource "sonarqube_qualitygate_condition" "new_coverage" {
  gatename  = sonarqube_qualitygate.default.name
  metric    = "new_coverage"
  op        = "LT"
  threshold = "50"
}
```

Which will no longer work because the `new_coverage` metric is already added when the gate is created but terraform state doesn't know about it - so you get this:

```
 Error: API returned an error: Condition on metric 'Coverage on New Code' already exists.

   with sonarqube_qualitygate_condition.new_coverage,
   on quality_gates.tf line 29, in resource "sonarqube_qualitygate_condition" "new_coverage":
   29: resource "sonarqube_qualitygate_condition" "new_coverage" {
```

I am not a GO developer but I played around with the provider and it seems like `resource_sonarqube_qualitygate.go` does not populate the `conditions` array when a gate is created.   It looks like it should but this seems to be a bug:
https://github.com/jdamata/terraform-provider-sonarqube/blob/e230cdf842cf6a0beaf46419903d8d0ed8e8ef52/sonarqube/resource_sonarqube_qualitygate.go#L182
at this point I guess the pointer to `resp.Body` is at the end of the body so `conditions` always remains empty.

Anyway I messed around a bit and fixed that to populate from `qualityGateReadResponse.Conditions` and now tf state will contain e.g.

```
resource "sonarqube_qualitygate" "default" {
    conditions = [
<snip>
        {
            error  = "80"
            id     = "AYe40uWkpq_IgwDfAktH"
            metric = "new_coverage"
            op     = "LT"
        },
    ]
    id         = "My way"
    is_default = true
    name       = "My way"
}
```

when the gate is created.
This still doesn't help with updating the conditions however since any new ones you create are in a completely different resource - e.g.:
```
resource "sonarqube_qualitygate_condition" "security_rating" {
    gatename  = "My way"
    id        = "AYe48en3pq_IgwDfAktJ"
    metric    = "security_rating"
    op        = "GT"
    threshold = "1"
}
```

It feels like the `sonarqube_qualitygate` resource needs to handle the conditions in  all cases and `sonarqube_qualitygate_condition` should be removed as it would be unnecessay at this point.
It is essentially useless for updating any of the conditions that SonarQube adds automatically now anyway.

And migrating to a new version of `sonarqube_qualitygate` could be a bit painful/a breaking change.

It feels like the sort of change that would require some discussion @jdamata rather than someone simply pushing a PR and hoping it is accepted :)

And of course there may be other solutions available....such as potentially `sonarqube_qualitygate_condition` updating the child resource within the `sonarqube_qualitygate` - though that may be a bit hacky even if it is possible?

### PR DESCRIPTION
**Pull request by freeranger**
fixes #154 

This PR address issues introduced in SonarQube 10 where conditions are automatically created for any new quality gates meaning terraform is unaware of them

* Refactored `sonarqube_qualitygate` to better model the relationship bet…ween the quality gate and it's conditions
* Removed `sonarqube_qualitygate_condition` as this is no longer required
* Addressed race condition when changing the default quality gate

### CODE REVIEW

File: sonarqube/resource_sonarqube_qualitygate.go [hunk 1]
```diff
@@ -60,23 +60,22 @@ func resourceSonarqubeQualityGate() *schema.Resource {
...
-				Description: "Name of the quality gate to set as default",
+				Description: "When set to true this Quality Gate is set as default",
 				Default:     false,
-				ForceNew:    true,
 			},
-			"conditions": {
+			"condition": {
 				Type:        schema.TypeList,
-				Computed:    true,
+				Optional:    true,
```
Comment (jdamata) [inline sonarqube/resource_sonarqube_qualitygate.go:78]: condition is a required field now right?

**Review by jdamata — APPROVED** [review]

**Comment by jdamata** [comment]
LGTM. After this is merged, can you rebase https://github.com/jdamata/terraform-provider-sonarqube/pull/161 from the master branch. I believe the tests will only pass when it gets the fixes you have put in

File: sonarqube/resource_sonarqube_qualitygate.go (hunk 1 above)
Comment (freeranger) [reply sonarqube/resource_sonarqube_qualitygate.go:78]: No because of `copy_from` - you must specify one or the other but you can’t have both

File: sonarqube/resource_sonarqube_qualitygate.go [hunk 2]
```diff
@@ -106,13 +105,18 @@ func resourceSonarqubeQualityGate() *schema.Resource {
...
 	if gate_to_copy, ok := d.GetOk("copy_from"); ok {
+		copying_gate = true
 		sonarQubeURL.Path = strings.TrimSuffix(sonarQubeURL.Path, "/") + "/api/qualitygates/copy"
 		sonarQubeURL.RawQuery = url.Values{
 			"name":       []string{d.Get("name").(string)},
 			"sourceName": []string{gate_to_copy.(string)},
 		}.Encode()
 	} else {
+		if _, ok := d.GetOk("condition"); !ok {
+			return fmt.Errorf("resourceQualityGateCreate: either copy_from or at least one condition block must be specified for a quality gate")
```
Comment (freeranger) [inline sonarqube/resource_sonarqube_qualitygate.go:118]: This ensures `copy_from` or at least one `condition` is supplied

File: sonarqube/resource_sonarqube_qualitygate.go [hunk 3]
```diff
@@ -60,23 +60,22 @@ func resourceSonarqubeQualityGate() *schema.Resource {
...
-				ForceNew: true,
 			},
 			"copy_from": {
-				Type:     schema.TypeString,
-				Optional: true,
-				ForceNew: true,
+				Type:          schema.TypeString,
+				Optional:      true,
+				ForceNew:      true,
+				ConflictsWith: []string{"condition"},
```
Comment (freeranger) [inline sonarqube/resource_sonarqube_qualitygate.go:68]: This ensures that you can’t specify both `copy_from` _and_ `condition`
